export const FETCH_SENT_DOCUMENTS_REQUEST = "FETCH_SENT_DOCUMENTS_REQUEST";
export const FETCH_SENT_DOCUMENTS_SUCCESS = "FETCH_SENT_DOCUMENTS_SUCCESS";
export const FETCH_SENT_DOCUMENTS_FAILURE = "FETCH_SENT_DOCUMENTS_FAILURE";
export const ADD_DOCUMENT_REQUEST = "ADD_DOCUMENT_REQUEST";
export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS";
export const ADD_DOCUMENT_FAILURE = "ADD_DOCUMENT_FAILURE";
