export const FETCH_SENT_DOCUMENTS_REQUEST = "FETCH_SENT_DOCUMENTS_REQUEST";
export const FETCH_SENT_DOCUMENTS_SUCCESS = "FETCH_SENT_DOCUMENTS_SUCCESS";
export const FETCH_SENT_DOCUMENTS_FAILURE = "FETCH_SENT_DOCUMENTS_FAILURE";
