export const CREATE_REQUEST_BEGIN = "CREATE_REQUEST_BEGIN";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_ERROR = "CREATE_REQUEST_ERROR";

export const GET_REQUESTS_BEGIN = "GET_REQUESTS_BEGIN";
export const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";

export const SET_EDIT_REQUEST = "SET_EDIT_REQUEST";
export const DELETE_REQUEST_BEGIN = "DELETE_REQUEST_BEGIN";

export const EDIT_REQUEST_BEGIN = "EDIT_REQUEST_BEGIN";
export const EDIT_REQUEST_SUCCESS = "EDIT_REQUEST_SUCCESS";
export const EDIT_REQUEST_ERROR = "EDIT_REQUEST_ERROR";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const OPEN_FILE = "OPEN_FILE";
