export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_REQUEST_BEGIN = "CREATE_REQUEST_BEGIN";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_ERROR = "CREATE_REQUEST_ERROR";

export const GET_REQUESTS_BEGIN = "GET_REQUESTS_BEGIN";
export const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";

export const SET_EDIT_REQUEST = "SET_EDIT_REQUEST";
export const DELETE_REQUEST_BEGIN = "DELETE_REQUEST_BEGIN";

export const EDIT_REQUEST_BEGIN = "EDIT_REQUEST_BEGIN";
export const EDIT_REQUEST_SUCCESS = "EDIT_REQUEST_SUCCESS";
export const EDIT_REQUEST_ERROR = "EDIT_REQUEST_ERROR";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const OPEN_FILE = "OPEN_FILE";
